name: Clear Cache

on:
  workflow_dispatch:

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clear Cache 🗑️
        run: npm cache clean --force
          
